version: "3.9"

services:
  api:
    build: .
    container_name: erp-api

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://erp_user:erp_password@postgres:5432/erp_integration

    depends_on:
      - postgres

    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: erp-postgres

    environment:
      POSTGRES_DB: erp_integration
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data: